### ISSUE TITLE
use qt5 to compille and ouput a erro

### ISSUE THREAD

**Issue by liguyano** [bterrier/qt-json-viewer#1]
C:\Users\kurum\OneDrive - jxstnu.edu.cn\c++\QT\qt-json-viewer\jsonmodel.cpp(117): error C2039: "resize": not a member of "QList<QPersistentModelIndex>" 
C:\QT\Qt5.12.2\5.12.2\msvc2017\include\QtCore/qlist.h(121): note: see the “QList<QPersistentModelIndex>” reference

**Comment by liguyano** [comment]
here is my cmake `cmake_minimum_required(VERSION 3.5)

project(json-viewer VERSION 0.1 LANGUAGES CXX)

set(CMAKE_INCLUDE_CURRENT_DIR ON)

set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_PREFIX_PATH "C:/QT/Qt5.12.2/5.12.2/msvc2017/lib/cmake")
set(QtLibs  Core Gui Xml Network Widgets)
find_package(Qt5 COMPONENTS
        ${QtLibs}
        REQUIRED)
add_executable(json-viewer
        main.cpp
        mainwindow.cpp
        mainwindow.h
        mainwindow.ui
        jsonmodel.h jsonmodel.cpp
)


target_link_libraries(json-viewer
        Qt5::Core
        Qt5::Gui
        Qt5::Widgets
        Qt5::Xml
        Qt5::Network
)

set_target_properties(json-viewer PROPERTIES
    MACOSX_BUNDLE_GUI_IDENTIFIER my.example.com
    MACOSX_BUNDLE_BUNDLE_VERSION ${PROJECT_VERSION}
    MACOSX_BUNDLE_SHORT_VERSION_STRING ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}
    MACOSX_BUNDLE TRUE
    WIN32_EXECUTABLE TRUE
)

if(QT_VERSION_MAJOR EQUAL 6)
    qt_finalize_executable(json-viewer)
endif()
`

**Comment by bterrier** [comment]
This project only works with Qt 6.
I won't solve Qt 5 issues.
